# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Whois-ARIN
version:      0.07
version_from: lib/Net/Whois/ARIN.pm
installdirs:  site
requires:
    Class::MethodMaker:            0
    IO::Socket::INET:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
