# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Whois-ARIN
version:      0.10
version_from: lib/Net/Whois/ARIN.pm
installdirs:  site
requires:
    IO::Socket::INET:              0
    Test::MockObject:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
